# Site settings
title: "Your Blog Title"
description: "A brief description of your blog."
author:
  name: "Your Name"
  avatar: "/assets/images/avatar.png"  # Optional: Add an image path here
url: "https://www.ibnalao.com"
baseurl: ""
include:
  - _pages

# Use Minimal Mistakes remote themee
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Minimal Mistakes settings
minimal_mistakes_skin: "default"  # You can choose other skin colors like "dark" or "air"
show_excerpts: true
excerpt_separator: "<!--more-->"

# Enable sidebar
sidebar:
  enabled: true
  sticky: true

# Pagination settings
pagination:
  enabled: true
  per_page: 5

# Plugins
plugins:
  - jekyll-include-cache

# Default settings for collections and posts
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"  # Use Minimal Mistakes layout for posts
  - scope:
      path: ""
    values:
      layout: "default"
