# Use Minimal Mistakes remote theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Site settings
locale: "en-US"
title: "Your Blog Title"
name: "Ibn Alao"
description: "This will capture my thoughts and Reflections on my Islamic Journey"
author:
  name: "Amir Alao"
  avatar: "/assets/images/avatar.png"  # Optional: Add an image path here
url: "https://www.ibnalao.com"
baseurl: ""
include:
  - _pages
  - _assets

# Minimal Mistakes settings
minimal_mistakes_skin: "dark"  # You can choose other skin colors like "dark" or "air"
show_excerpts: true
excerpt_separator: "<!--more-->"

# Enable sidebar
sidebar:
  enabled: true
  sticky: true

# Pagination settings
pagination:
  enabled: true
  per_page: 5

# Plugins
plugins:
  - jekyll-include-cache

# Default settings for collections and posts
collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"  # Use Minimal Mistakes layout for posts
  - scope:
      path: ""
    values:
      layout: "default"
